name: Convert Report to PDF

on:
  workflow_dispatch:
    inputs:
      report:
        description: 'Report to convert'
        required: true
        type: choice
        # TODO options to be called from a script or code
        options:
        - Aciclovir-Mean
        - Aciclovir-Mean-SVG
        - Aciclovir-Population
        - Raltegravir-Absorption
        - Raltegravir-Mass-Balance
        - Test-NO7
        - Test-NO8
        - Test-NO9
        - Test-NO10
        - Test-NO11
        - Test-NO12
  
jobs:
  report-to-pdf:
    runs-on: ubuntu-latest
    # Allow only authorized collaborators to trigger GA:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
# All steps in workflow:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pandoc and wkhtmltopdf
        run: |
          sudo apt update
          sudo apt install pandoc
      - name: Perform html conversion with pandoc
        run: |
          pandoc -f markdown -t html5 \
          -o Reports/${{ inputs.report }}/Report.html \
          Reports/${{ inputs.report }}/Report.md -c osp.css
      - name: Save PDF file as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.report }}-html
          path: Reports/${{ inputs.report }}/Report.html
