name: Convert Report to PDF

on:
  workflow_dispatch:
    inputs:
      report:
        description: 'Report to convert'
        required: true
        type: choice
        # TODO options to be called from a script or code
        options:
        - Aciclovir-Mean
        - Aciclovir-Mean-SVG
        - Aciclovir-Population
        - Raltegravir-Absorption
        - Raltegravir-Mass-Balance
        - Test-NO7
        - Test-NO8
        - Test-NO9
        - Test-NO10
        - Test-NO11
        - Test-NO12
  
jobs:
  report-to-pdf:
    runs-on: ubuntu-latest
    # Allow only authorized collaborators to trigger GA:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
# All steps in workflow:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pandoc and wkhtmltopdf
        run: |
          sudo apt update
          sudo apt install pandoc
          sudo apt install wkhtmltopdf
      - name: Perform pdf conversion using pandoc
        run: |
          pandoc -f gfm -t html5 --metadata pagetitle="Test Report" --css osp.css \
          --pdf-engine-opt="--enable-local-file-access" \
          --pdf-engine-opt="--enable-external-links" \
          --pdf-engine-opt="--keep-relative-links" \
          --pdf-engine-opt="--enable-smart-shrinking"
          Reports/${{ inputs.report }}/Report.md -o Reports/${{ inputs.report }}/Report.pdf
      - name: Save PDF file as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.report }}-pdf
          path: Reports/${{ inputs.report }}/Report.pdf
