name: Update website
on:
  workflow_run:
    workflows: ["Run RE Report Tests"]
    types:
      - completed
# The action needs permissions to update the branch
permissions:
  contents: write
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          
jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      # No need to install ospsuite ecosystem
      # because the job only needs to display the md reports as html pages
      - name: Packages to build website
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::jsonlite, any::rmarkdown, any::pkgdown
      # The script temporarily create index and vignettes for pkgdown to build site
      - name: Build customized site using RScript
        run: Rscript .github/workflows/build-site.R
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        # The deployment folder should match the name of the artifact.
        # Clean is false to prevent removing release site
        # only target folder of repo from gh-pages branch is updated
        with:
          folder: docs
          clean: true
          branch: gh-pages
          target-folder: docs
          token: ${{ secrets.GITHUB_TOKEN }}
